name: uhealth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  permission_handler: ^11.2.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.13.1
  google_fonts: ^6.1.0
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  pie_chart: ^5.4.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  http: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/img/
